Task review

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,14 +1,23 @@
-#!/usr/bin/env bash
-# Transfers a file from Holberton's client to another.
-# Accepts four arguments:
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
+#!/bin/bash
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if the number of parameters is less than 4
+if [ "$#" -ne 4 ]; then
+    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables for better readability
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# Use scp to transfer the file to the user's home directory on the server
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
+
+# Check if the scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "File transfer failed."
 fi
